### ISSUE TITLE
Object missing in this sentence

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/js-object-oriented-class-relations-lab#7]
Need an object in this bullet item, literally:

new Trip() - initialized with an instance of driver and an instance of passenger; returns a JavaScript that has attributes id, driverId, and passengerId

Proposed edit, based on the previous bullet in the lesson:
...returns a JavaScript object

Thank you.

**Comment by drakeltheryuujin** [comment]
We have updated the materials and the issue to has been resolved.
